<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['pat_Patients'] = array(
    'table' => 'pat_patients',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array (
  'nas_perso' => 
  array (
    'required' => false,
    'name' => 'nas_perso',
    'vname' => 'LBL_NAS_PERSO',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'nas_perso_' => 
  array (
    'required' => false,
    'name' => 'nas_perso_',
    'vname' => 'LBL_NAS_PERSO_',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '9',
    'size' => '20',
  ),
  'tel_dom_perso' => 
  array (
    'required' => false,
    'name' => 'tel_dom_perso',
    'vname' => 'LBL_TEL_DOM_PERSO',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'tel_travail_perso' => 
  array (
    'required' => false,
    'name' => 'tel_travail_perso',
    'vname' => 'LBL_TEL_TRAVAIL_PERSO',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'tel_mobile_perso' => 
  array (
    'required' => false,
    'name' => 'tel_mobile_perso',
    'vname' => 'LBL_TEL_MOBILE_PERSO',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'nom' => 
  array (
    'required' => false,
    'name' => 'nom',
    'vname' => 'LBL_NOM',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'prenom' => 
  array (
    'required' => false,
    'name' => 'prenom',
    'vname' => 'LBL_PRENOM',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'email_perso' => 
  array (
    'required' => false,
    'name' => 'email_perso',
    'vname' => 'LBL_EMAIL_PERSO',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'validation' => 
    array (
      'type' => 'callback',
      'callback' => 'function(formname,nameIndex){ console.log(formname, nameIndex, "WTF???"); return true; }',
    ),
  ),
  'naissance_perso' => 
  array (
    'required' => false,
    'name' => 'naissance_perso',
    'vname' => 'LBL_NAISSANCE_PERSO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'emploi_perso' => 
  array (
    'required' => false,
    'name' => 'emploi_perso',
    'vname' => 'LBL_EMPLOI_PERSO',
    'type' => 'SmartDropdown',
    'isMultiSelect' => true,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quel est votre emploi du temps principal ?',
    'qdetail_en' => 'What is your main use of time?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'emploi_temps_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'education_perso' => 
  array (
    'required' => false,
    'name' => 'education_perso',
    'vname' => 'LBL_EDUCATION_PERSO',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quel est votre plus haut niveau complété d\'éducation',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'niveau_education_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'education_perso_autre' => 
  array (
    'required' => false,
    'name' => 'education_perso_autre',
    'vname' => 'LBL_EDUCATION_PERSO_AUTRE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'groupe_designe' => 
  array (
    'required' => false,
    'name' => 'groupe_designe',
    'vname' => 'LBL_GROUPE_DESIGNE',
    'type' => 'SmartDropdown',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'groupe_minoritaire_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'etabl_sante_pa' => 
  array (
    'required' => false,
    'name' => 'etabl_sante_pa',
    'vname' => 'LBL_ETABL_SANTE_PA',
    'type' => 'SmartDropdown',
    'options' => 'etab_sante_list',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Dans quel établissement de santé le pp se fait-il principalement traiter ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'code_ident' => 
  array (
    'required' => true,
    'name' => 'code_ident',
    'vname' => 'LBL_CODE_IDENT',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
  ),
  'doul_chron' => 
  array (
    'required' => false,
    'name' => 'doul_chron',
    'vname' => 'LBL_DOUL_CHRON',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Le pp a-t-il des douleurs chroniques ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'prob_somm' => 
  array (
    'required' => false,
    'name' => 'prob_somm',
    'vname' => 'LBL_PROB_SOMM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Le pp a-t-il des proiblèmes de sommeil ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'prob_resp' => 
  array (
    'required' => false,
    'name' => 'prob_resp',
    'vname' => 'LBL_PROB_RESP',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Le pp a-t-il des proiblèmes de respiration ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'experience_maladie_proche' => 
  array (
    'required' => false,
    'name' => 'experience_maladie_proche',
    'vname' => 'LBL_EXPERIENCE_MALADIE_PROCHE',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Pouvez-vous décrire l\'expérience avec la maladie de votre proche? Pouvez-vous décrire votre implication dans le parcours de soins de votre proche? ',
    'qdetail_en' => 'What is your family member\'s experience with illness?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'rel_patient' => 
  array (
    'required' => false,
    'name' => 'rel_patient',
    'vname' => 'LBL_REL_PATIENT',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'relation_patient_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'domaine_soin_pa' => 
  array (
    'required' => false,
    'name' => 'domaine_soin_pa',
    'vname' => 'LBL_DOMAINE_SOIN_PA',
    'type' => 'SmartDropdown',
    'options' => 'specialites_soin_list',
    'isMultiSelect' => true,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'domaine_soin_pa_2' => 
  array (
    'required' => false,
    'name' => 'domaine_soin_pa_2',
    'vname' => 'LBL_DOMAINE_SOIN_PA_2',
    'type' => 'SmartDropdown',
    'options' => 'specialites_soin_list',
    'isMultiSelect' => true,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'domaine_soin_pa_3' => 
  array (
    'required' => false,
    'name' => 'domaine_soin_pa_3',
    'vname' => 'LBL_DOMAINE_SOIN_PA_3',
    'type' => 'SmartDropdown',
    'options' => 'specialites_soin_list',
    'isMultiSelect' => true,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'prob_sant_pa' => 
  array (
    'required' => false,
    'name' => 'prob_sant_pa',
    'vname' => 'LBL_PROB_SANT_PA',
    'type' => 'SmartDropdown',
    'isMultiSelect' => true,
    'options' => 'cim10_list',
    'len' => '1024',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
    'dbType' => 'varchar',
  ),
  'prob_sant_pa_2' => 
  array (
    'required' => false,
    'name' => 'prob_sant_pa_2',
    'vname' => 'LBL_PROB_SANT_PA_2',
    'type' => 'SmartDropdown',
    'options' => 'cim10_list',
    'len' => 1024,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'prob_sant_pa_3' => 
  array (
    'required' => false,
    'name' => 'prob_sant_pa_3',
    'vname' => 'LBL_PROB_SANT_PA_3',
    'type' => 'SmartDropdown',
    'options' => 'cim10_list',
    'len' => 1024,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'etabl_sante_pa_' => 
  array (
    'required' => false,
    'name' => 'etabl_sante_pa_',
    'vname' => 'LBL_ETABL_SANTE_PA_',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'etabl_prem_ligne_pa_' => 
  array (
    'required' => false,
    'name' => 'etabl_prem_ligne_pa_',
    'vname' => 'LBL_ETABL_PREM_LIGNE_PA_',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'membre_assoc_comite_detail' => 
  array (
    'required' => false,
    'name' => 'membre_assoc_comite_detail',
    'vname' => 'LBL_MEMBRE_ASSOC_COMITE_DETAIL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Si oui, laquelle ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'conflit_interet' => 
  array (
    'required' => false,
    'name' => 'conflit_interet',
    'vname' => 'LBL_CONFLIT_INTERET',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'En vue du projet sur lequel vous êtes appelé à collaborer comme patient partenaire, existe-t-il des situations qui pourraient représenter un conflit d\'intérêt réel ou potentiel (ex. membre d\'une association militante, votre employeur, intérêts financiers personnels, gains pour moi ou un proche par rapport à un accès à certains soins, engagement idéologique) ?',
    'qdetail_en' => 'In view of the project on which you are called upon to collaborate as a patient partner, are there any situations that could represent an actual or potential conflict of interest (e. g. member of an activist association, your employer, personal financial interests, earnings for me or a relative in relation to access to certain care, ideological commitment)?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'membre_assoc_comite' => 
  array (
    'required' => false,
    'name' => 'membre_assoc_comite',
    'vname' => 'LBL_MEMBRE_ASSOC_COMITE',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Nous aimerions connaître vos implications. Êtes vous membre d\'une association ou d\'un comité en lien - ou NON - avec votre expérience avec la maladie ?',
    'qdetail_en' => 'Please indicate if you may have any involvements that are  (or are not) related to your experience with your illness',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'motivations_implication' => 
  array (
    'required' => false,
    'name' => 'motivations_implication',
    'vname' => 'LBL_MOTIVATIONS_IMPLICATION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quelles sont vos motivations à vous impliquer à titre de patient partenaire ?',
    'qdetail_en' => 'What are your motivations for getting involved as a patient partner?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'disponibilites' => 
  array (
    'required' => false,
    'name' => 'disponibilites',
    'vname' => 'LBL_DISPONIBILITES',
    'type' => 'SmartDropdown',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quelles sont vos préférences de disponibilité ?',
    'qdetail_en' => 'What are your preferred availabilities?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'disponibilites_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'preferences' => 
  array (
    'required' => false,
    'name' => 'preferences',
    'vname' => 'LBL_PREFERENCES',
    'type' => 'SmartDropdown',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quels sont vos champs d\'intérêt pour vous impliquer à titre de patient partenaires ?',
    'qdetail_en' => 'What are your preferred areas of involvement?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'preferences_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'duree_experience' => 
  array (
    'required' => false,
    'name' => 'duree_experience',
    'vname' => 'LBL_DUREE_EXPERIENCE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Au total, depuis combien de temps pensez-vous être impliqué dans des associations, comités, ou autre ?',
    'qdetail_en' => 'In total, how long do you think you have been involved in associations, committees, or other organizations?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'exp_sante' => 
  array (
    'required' => false,
    'name' => 'exp_sante',
    'vname' => 'LBL_EXP_SANTE',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous déjà travaillé dans le milieu de santé?',
    'qdetail_en' => 'Have you previously worked in healthcare?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'descr_exp' => 
  array (
    'required' => false,
    'name' => 'descr_exp',
    'vname' => 'LBL_DESCR_EXP',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Pouvez-vous expliquer ?',
    'qdetail_en' => 'Could you briefly describe the experience you have had as a patient partner?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'formation_pp' => 
  array (
    'required' => false,
    'name' => 'formation_pp',
    'vname' => 'LBL_FORMATION_PP',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous déjà suivi une formation sur le partenariat patient ?',
    'qdetail_en' => 'Have you ever followed a patient partnership workshop/webinar/training?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'formation_oui' => 
  array (
    'required' => false,
    'name' => 'formation_oui',
    'vname' => 'LBL_FORMATION_OUI',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Laquelle ?',
    'qdetail_en' => 'What was it called?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'formation_qui' => 
  array (
    'required' => false,
    'name' => 'formation_qui',
    'vname' => 'LBL_FORMATION_QUI',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Par quel organisme a-t-elle été donnée? + où, quand, etc,…',
    'qdetail_en' => 'Which organisation/institution delivered this workshop/webinar/training?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'competences_pp' => 
  array (
    'required' => false,
    'name' => 'competences_pp',
    'vname' => 'LBL_COMPETENCES_PP',
    'type' => 'SmartDropdown',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Suite à l\'entrevue, quelles compétences peuvent être identifiées chez le PP ?',
    'qdetail_en' => 'Following the interview, what skills can be identified in the patient partner?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'competences_pp_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'competences_pr' => 
  array (
    'required' => false,
    'name' => 'competences_pr',
    'vname' => 'LBL_COMPETENCES_PR',
    'type' => 'SmartDropdown',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Suite à l\'entrevue, quelles compétences peuvent être identifiées chez le PRessource ?',
    'qdetail_en' => 'Following the interview, what skills can be identified in the patient resource?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'competences_pr_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'competences_ppc' => 
  array (
    'required' => false,
    'name' => 'competences_ppc',
    'vname' => 'LBL_COMPETENCES_PPC',
    'type' => 'SmartDropdown',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Suite à l\'entrevue, quelles compétences peuvent être identifiées chez le PProfilCoach ?',
    'qdetail_en' => 'Following the interview, what skills can be identified in the patient coach?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'competences_ppc_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'habiletes_pp' => 
  array (
    'required' => false,
    'name' => 'habiletes_pp',
    'vname' => 'LBL_HABILETES_PP',
    'type' => 'SmartDropdown',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quelles habiletés ou aptitudes personnelles peuvent être identifiées ?',
    'qdetail_en' => 'Following the interview, what personal aptitudes can be identified in the patient partner?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'habilites_pp_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'patient_ajout' => 
  array (
    'required' => false,
    'name' => 'patient_ajout',
    'vname' => 'LBL_PATIENT_AJOUT',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous d\'autres choses à ajouter ?',
    'qdetail_en' => 'Please indicate any additional comments',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'comm_recruteur' => 
  array (
    'required' => false,
    'name' => 'comm_recruteur',
    'vname' => 'LBL_COMM_RECRUTEUR',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Commentaires du recruteur ?',
    'qdetail_en' => 'Recruter comments',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'langue_parlee' => 
  array (
    'required' => false,
    'name' => 'langue_parlee',
    'vname' => 'LBL_LANGUE_PARLEE',
    'type' => 'SmartDropdown',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quelles langues parlez-vous couramment parmi les suivantes ?',
    'qdetail_en' => 'Please identify all languages you speak fluently',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'langue_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'langue_corresp' => 
  array (
    'required' => false,
    'name' => 'langue_corresp',
    'vname' => 'LBL_LANGUE_CORRESP',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quelle est votre langue de correspondance préférée',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'langue_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'niveau_mob' => 
  array (
    'required' => false,
    'name' => 'niveau_mob',
    'vname' => 'LBL_NIVEAU_MOB',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous besoin d\'accompagnement spécifique pour la mobilité réduite ?',
    'qdetail_en' => 'Do you require any specific support for reduced mobility?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'niveau_aud' => 
  array (
    'required' => false,
    'name' => 'niveau_aud',
    'vname' => 'LBL_NIVEAU_AUD',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous des problèmes d\'audition ?',
    'qdetail_en' => 'Do you have hearing problems?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'niveau_vue' => 
  array (
    'required' => false,
    'name' => 'niveau_vue',
    'vname' => 'LBL_NIVEAU_VUE',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous des problèmes de la vision ?',
    'qdetail_en' => 'Do you have eyesight problems ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'niveau_fatigabilite' => 
  array (
    'required' => false,
    'name' => 'niveau_fatigabilite',
    'vname' => 'LBL_NIVEAU_FATIGABILITE',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous besoin d\'accompagnement spécifique au niveau fatigabilité ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'niveau_autre' => 
  array (
    'required' => false,
    'name' => 'niveau_autre',
    'vname' => 'LBL_NIVEAU_AUTRE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Précisez d\'autres accompagnements dont vous avez besoin',
    'qdetail_en' => 'Please indicate any additional support you may require',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'association_etablissement_recr' => 
  array (
    'required' => false,
    'name' => 'association_etablissement_recr',
    'vname' => 'LBL_ASSOCIATION_ETABLISSEMENT_RECR',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'À quel établissement sera associé le PP ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'etablissement_recrut_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'date_entrevue' => 
  array (
    'required' => false,
    'name' => 'date_entrevue',
    'vname' => 'LBL_DATE_ENTREVUE',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Inscrire la date',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'recruteur' => 
  array (
    'required' => false,
    'name' => 'recruteur',
    'vname' => 'LBL_RECRUTEUR',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Identifier le recruteur',
    'qdetail_en' => 'Identification of the recruter',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'personne_reference_recrut' => 
  array (
    'required' => false,
    'name' => 'personne_reference_recrut',
    'vname' => 'LBL_PERSONNE_REFERENCE_RECRUT',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous été référé par une personne? Si oui, qui ?',
    'qdetail_en' => 'Have you been referred by someone? If yes, please specify',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'comment_refere' => 
  array (
    'required' => false,
    'name' => 'comment_refere',
    'vname' => 'LBL_COMMENT_REFERE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Comment avez-vous été référé ?',
    'qdetail_en' => 'How have you been referred?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'org_ref_recrut' => 
  array (
    'required' => false,
    'name' => 'org_ref_recrut',
    'vname' => 'LBL_ORG_REF_RECRUT',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quel organisme ?',
    'qdetail_en' => 'Recruting organisation',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'consentement_dcpp_recrut' => 
  array (
    'required' => false,
    'name' => 'consentement_dcpp_recrut',
    'vname' => 'LBL_CONSENTEMENT_DCPP_RECRUT',
    'type' => 'BlockingRadioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Est-ce que vous consentez à vous impliquer en tant que patient partenaire ?',
    'qdetail_en' => 'Do you consent to adopting a patient partner role?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'consentement_recherche' => 
  array (
    'required' => false,
    'name' => 'consentement_recherche',
    'vname' => 'LBL_CONSENTEMENT_RECHERCHE',
    'type' => 'BlockingRadioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Acceptez-vous que vos données en lien avec votre implication en tant que patient partenaire soient potentiellement utilisées à des fins de recherche ?',
    'qdetail_en' => 'Do you agree to data generated by your patient partner interactions being used for research purposes?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'consentement_usage_donnees' => 
  array (
    'required' => false,
    'name' => 'consentement_usage_donnees',
    'vname' => 'LBL_CONSENTEMENT_USAGE_DONNEES',
    'type' => 'BlockingRadioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Consentez-vous à faire partie de la banque de données ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
    'qdetail_en' => 'Do you consent to data concerning you being stored in a database?',
  ),
  'consentement_miseajour' => 
  array (
    'required' => false,
    'name' => 'consentement_miseajour',
    'vname' => 'LBL_CONSENTEMENT_MISEAJOUR',
    'type' => 'BlockingRadioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Acceptez-vous qu\'on communique avec vous annuellement pour des fins de mise à jour de vos informations? ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'etat' => 
  array (
    'required' => false,
    'name' => 'etat',
    'vname' => 'LBL_ETAT',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'etat_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'genre' => 
  array (
    'required' => false,
    'name' => 'genre',
    'vname' => 'LBL_GENRE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'genre_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'conflit_interet_detail' => 
  array (
    'required' => false,
    'name' => 'conflit_interet_detail',
    'vname' => 'LBL_CONFLIT_INTERET_DETAIL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Si oui, lesquels?',
    'qdetail_en' => 'If yes, please specify',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'centre_recrutement' => 
  array (
    'required' => false,
    'name' => 'centre_recrutement',
    'vname' => 'LBL_CENTRE_RECRUTEMENT',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'assistance_mob' => 
  array (
    'required' => false,
    'name' => 'assistance_mob',
    'vname' => 'LBL_ASSISTANCE_MOB',
    'type' => 'SmartDropdown',
    'options' => 'aides_mobilite_list',
    'isMultiSelect' => true,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Veuillez sélectionner toute option qui s\'applique',
    'qdetail_en' => 'Please select any option that applies',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'role_pp' => 
  array (
    'required' => false,
    'name' => 'role_pp',
    'vname' => 'LBL_ROLE_PP',
    'type' => 'SmartDropdown',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Quel était votre rôle ?',
    'qdetail_en' => 'What was your role?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'role_pp_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'assistance_audition' => 
  array (
    'required' => false,
    'name' => 'assistance_audition',
    'vname' => 'LBL_ASSISTANCE_AUDITION',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous besoin d\'assistance ?',
    'qdetail_en' => 'Do you require any specific support for hearing?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'assistance_vision' => 
  array (
    'required' => false,
    'name' => 'assistance_vision',
    'vname' => 'LBL_ASSISTANCE_VISION',
    'type' => 'radioenum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Avez-vous besoin d\'assistance ?',
    'qdetail_en' => 'Do you require any specific support for eyesight?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'experience_maladie_pp' => 
  array (
    'required' => false,
    'name' => 'experience_maladie_pp',
    'vname' => 'LBL_EXPERIENCE_MALADIE_PP',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'qdetail' => 'Pouvez-vous expliquer ?',
    'qdetail_en' => 'Can you elaborate ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'experience_maladie_pa' => 
  array (
    'required' => false,
    'name' => 'experience_maladie_pa',
    'vname' => 'LBL_EXPERIENCE_MALADIE_PA',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
    'qdetail' => 'Pouvez-vous décrire votre expérience comme pair aidant ?',
    'qdetail_en' => 'What is your experience as a carer to this person?',
  ),
  'exp_sante_detail' => 
  array (
    'required' => false,
    'name' => 'exp_sante_detail',
    'vname' => 'LBL_EXP_SANTE_DETAIL',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
    'qdetail' => 'Si oui, quelle est votre expérience dans le milieu de santé hors de votre expérience avec la maladie ?',
    'qdetail_en' => 'If so, what was your experience like of the healthcare system (outside of your illness)?',
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('pat_Patients', 'pat_Patients', array('basic','assignable','security_groups','person'));